Я сделялъ
skypro-008/lesson22-and-tests pull request #1
Opened 2021-12-22 21:52 UTC by OlegKuro

2021-12-23 19:02 UTC, painassasin requested changes

2021-12-23 19:02 UTC, painassasin commented on part1/practice/bad_smell_comments/main.py
> +            speed *= 0.5
Код повторяется, меняется только speed

2021-12-23 19:02 UTC, painassasin commented on part1/practice/bad_smell_long_parameter_list/main.py
> +    def set_unit(self, unit, coords):
Зачем метод, если эти параметры можно определить в __init__?

2021-12-23 20:18 UTC, OlegKuro commented on part1/practice/bad_smell_long_parameter_list/main.py
> +    def set_unit(self, unit, coords):
можно, но DTO запроса обычно иммутабельны

т.е. я если я сделаю `request.field = Field(*args, **kwargs)`, я поменяю поле только в DTO
а вот если сеттером поменяю внутреннее состояние класса, то все будет вести себя точно так же, как и в исходном коде

если бы метод возвращал поле, то тоже можно было конструктором создать новый инстанс и не было бы сайд-эффектов)

2021-12-23 20:18 UTC, OlegKuro commented on part1/practice/bad_smell_comments/main.py
> +            speed *= 0.5
точно! спасибо!

2021-12-24 21:50 UTC, OlegKuro commented on part1/practice/bad_smell_long_parameter_list/main.py
> +    def set_unit(self, unit, coords):
но как я конструктор заюзаю этот, если у меня field параметром приходит

и в задании тоже

2021-12-26 00:58 UTC, closed without merging